apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo-1-hello-world
resources:
  - ../../base
  - namespace.yaml
patches:
  - path: patch-replicas.yaml
  - path: patch-index.yaml
